name: Publish Common Python

on:
  push:
    tags:
      - "common-py-v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: extract_version
        run: |
          tag_name="${GITHUB_REF##*/}"
          version="${tag_name#common-py-v}"
          echo "Extracted version: $version"
          echo "NEW_VERSION=$version" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build tools
        run: pip install build twine

      - name: Set version
        run: |
          cd common/python
          sed -i "s/__version__ = .*/__version__ = \"${{ env.NEW_VERSION }}\"/" maxcompute_tea_openapi/__init__.py

      - name: Build package
        run: |
          cd common/python
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: common/python/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
